const BlogData = [
  {
    id: 1,
    date: "Oct 21, 2023",
    catgeory: "Technology",
    title: "Math Modeling Challenge",
    cover: "/Images/news/2/1.jpg",
    para: "El Math Modeling Challenge CoSIAM (MMC CoSIAM) es un concurso de modelamiento matemático, tipo hackday, en el que equipos de estudiantes provenientes de distintas universidades de Colombia y algunas invitadas del exterior.",
    desc: "El Math Modeling Challenge CoSIAM (MMC CoSIAM) es un concurso de modelamiento matemático, tipo hackday, en el que equipos de estudiantes provenientes de distintas universidades de Colombia, proponen una solución a un problema del sector empresarial, a través de distintas herramientas de las matemáticas aplicadas. Todo lo anterior bajo ciertas restricciones de tiempo y recursos. El MMC CoSIAM 2023 convoca equipos formado máximo por cuatro (4) estudiantes de pregrado o posgrado. Cada estudiante debe estar adscrito a algún programa académico de una universidad perteneciente a uno de los Nodos CoSIAM. Es deseable que los equipos estén conformados por estudiantes de distintas programas académicos, con fin de potenciar el trabajo multidisciplinar en cada equipo.",
  },
  {
    id: 2,
    date: "Dic, 2023",
    catgeory: "Technology",
    title: "Workshop and International Seminar on Complexity Sciences CoSIAM",
    cover: "/Images/news/2/2.jpg",
    para: "Conoce El Workshop and International Seminar on Complexity Science WISCS CoSIAM, un evento académico especializado, multi-institucional e interdisciplinar, para el desarrollo de la investigación en Colombia desde la matemática aplicadas.",
    desc: "El Workshop and International Seminar on Complexity Science WISCS CoSIAM es un evento académico especializado, multi-institucional e interdisciplinar, para el desarrollo de la investigación en Colombia desde la matemática aplicada, en el que expertos obtienen realimentación especializada para el fortalecimiento de sus trabajos científicos. El WISCS CoSIAM brinda una plataforma especializada para que los investigadores presenten sus trabajos científicos y reciban realimentación de expertos en el campo. Esta retroalimentación es valiosa para mejorar la calidad de la investigación y fomentar el avance del conocimiento en la matemática aplicada y las ciencias de la complejidad.",
  },
  {
    id: 3,
    date: "Por confirmar",
    catgeory: "Developement",
    title: "Escuela de Matemática Aplicada e Industrial",
    cover: "/Images/news/2/3.jpg",
    para: "Este es un evento ideal para estudiantes y profesionales interesados en aprender las técnicas de la matemática aplicada e industrial e inspirarse con las experiencias exitosas de expertos de nuestra comunidad.",
    desc: "La Escuela de Matemática Aplicada e Industrial CoSIAM es un evento académico de gran relevancia que reúne a estudiantes, profesores, investigadores y profesionales de diversas instituciones nacionales e internacionales. Durante esta emocionante semana, se lleva a cabo un cursillo de matemática aplicada que aborda temas de vanguardia en esta área. Los participantes tienen la oportunidad de profundizar en conceptos y técnicas avanzadas, así como de explorar aplicaciones prácticas en diferentes campos, desde la ingeniería hasta la biología y la economía.",
  },
  {
    id: 4,
    date: "Cursillo 2022",
    catgeory: "Machine Learning",
    title: "Artifical Intelligence and Machine Learning",
    cover: "/Images/news/3/1.jpg",
    para: "En este cursillo se utilizará la tecnología de google cloud para identificar y realizar tareas de procesamiento del lenguaje. Encontrarás una introducción al procesamiento de imágenes con google cloud, introducción al procesamiento del lenguaje natural con google cloud, APIS de Google para Machine Learning.",
    desc: "En este cursillo se utilizará la tecnología de google cloud para identificar y realizar tareas de procesamiento del lenguaje. Encontrarás una introducción al procesamiento de imágenes con google cloud, introducción al procesamiento del lenguaje natural con google cloud, APIS de Google para Machine Learning.",
  },
  {
    id: 5,
    date: "Cursillo 2022",
    catgeory: "Computer Science",
    title: "Complex Networks",
    cover: "/Images/news/6/2.jpg",
    para: "Este cursillo busca brindar una introducción y fundamentación de redes compleja, abarcando temas como medidas de centralidad, estructura en redes, simulación de procesos con redes complejas.",
    desc: "Este cursillo busca brindar una introducción y fundamentación de redes compleja, abarcando temas como medidas de centralidad, estructura en redes, simulación de procesos con redes complejas.",
  },
  {
    id: 6,
    date: "Cursillo 2022",
    catgeory: "Computer Science",
    title: "System Dynamics",
    cover: "/Images/news/5/3.jpeg",
    para: "El cursillo permitirá ampliar el conocimiento en aplicaciones de la dinámica de sistemas, se presentarán aplicaciones reconocidas de la Dinámica de Sistemas y se discutirá sobre lo qué es, sobre lo qué no es, sobre sus posibilidades para la resolución de problemas en diferentes contextos y sobre su método de modelamiento.",
    desc: "El cursillo permitirá ampliar el conocimiento en aplicaciones de la dinámica de sistemas, se presentarán aplicaciones reconocidas de la Dinámica de Sistemas y se discutirá sobre lo qué es, sobre lo qué no es, sobre sus posibilidades para la resolución de problemas en diferentes contextos y sobre su método de modelamiento.",
  },
  {
    id: 7,
    date: "Cursillo 2021",
    catgeory: "Dynamical Systems",
    title: "Dinamica en sistemas electricos",
    cover: "/Images/news/1/2.jpeg",
    para: "En este cursillo estudiarás el comportamiento y la interacción de los componentes eléctricos en un sistema en movimiento. Examina cómo los circuitos eléctricos, dispositivos y fuentes de energía interactúan y responden a cambios en las condiciones de operación.",
    desc: "En este cursillo estudiarás el comportamiento y la interacción de los componentes eléctricos en un sistema en movimiento. Examina cómo los circuitos eléctricos, dispositivos y fuentes de energía interactúan y responden a cambios en las condiciones de operación.",
  },
  {
    id: 8,
    date: "Cursillo 2021",
    catgeory: "Blockchain",
    title: "Blockchain y contratos inteligentes",
    cover: "/Images/news/1/1.jpeg",
    para: "Aprenderás herramientas utilizadass en diversas aplicaciones, como transacciones financieras, gestión de activos digitales, votaciones y cadenas de suministro, proporcionando una mayor eficiencia, seguridad y transparencia en las operaciones.",
    desc: "Aprenderás herramientas utilizadass en diversas aplicaciones, como transacciones financieras, gestión de activos digitales, votaciones y cadenas de suministro, proporcionando una mayor eficiencia, seguridad y transparencia en las operaciones.",
  },
  {
    id: 9,
    date: "Cursillo 2021",
    catgeory: "Computer Science",
    title: "Optimización cuadrática y máquinas de vectores de soporte",
    cover: "/Images/news/1/3.jpg",
    para: "Aprenderás cómo desarrollar una resolución de problemas que involucren una función objetivo cuadrática y restricciones lineales. Esta técnica matemática es ampliamente utilizada para encontrar soluciones óptimas en diversos campos, como la estadística, la ingeniería y la ciencia de datos.",
    desc: "Aprenderás cómo desarrollar una resolución de problemas que involucren una función objetivo cuadrática y restricciones lineales. Esta técnica matemática es ampliamente utilizada para encontrar soluciones óptimas en diversos campos, como la estadística, la ingeniería y la ciencia de datos.",
  },
]

export default BlogData
